### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by mastacheata** [illuminate/socialite#7]
May I suggest tagging a new version so the changes you merged last year (guzzle 3.x and the improved getCurrentUrl) are available without requiring the @dev version of socialite?

I'm completely aware that this is not really a top-priority project for you and I've been working with it for the last year without any problems. It just came back to my mind when I just set up a new project using the socialite package that I still need to use the @dev stability flag.

**Comment by taylorotwell** [comment]
I will when its done.
